### ISSUE TITLE
About NVMe-TCP offload implemenation

### ISSUE THREAD

**Issue by jackcost6** [BorisPis/autonomous-asplos21-artifact#1]
Hi，
Is the source code of NVMe-TCP NIC offload merged into this git repository？
In your paper “Autonomous NIC Offloads”， 𝑐𝑟𝑐_𝑜𝑘 bit in SKB is used for describing the status of CRC verification, and magic pattern of NVMe-TCP use PDU Header and digest for speculative searching. But these codes are not found in this git repository, I only see  offload emulation feature and skipping crc operation in NVMe-TCP part. So I want to comfirm NVMe-TCP offload implemenation is not in this git repository, right?

Thank you.

**Comment by BorisPis** [comment]
Right. In this repository we emulate nvme-tcp by skipping. There is upstream work on ConnectX-7 support for this feature, you can find the latest series here:
https://patches.linaro.org/project/netdev/cover/20210211211044.32701-1-borisp@mellanox.com/

That series contains only the receive side, there are patches for the transmit side, and these will be submitted after work on receive side offloads is complete.
